name: neyimeshur
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_bloc: ^9.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  flutter_keyboard_visibility: ^6.0.0
  colorful_safe_area: ^1.0.0
  google_maps_flutter: ^2.10.0
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  shared_preferences: ^2.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
flutter:
  uses-material-design: true
  assets:
    - assets/images/